### ISSUE TITLE
Cache not updated by default on CanvasGetAppSurf() if setting __writeToCache to false

### ISSUE THREAD

**Issue by patchuby** [tabularelf/Canvas#4]
Fix is line 21 of CanvasGetAppSurf function
<img width="512" alt="image" src="https://github.com/tabularelf/Canvas/assets/9586594/07d8362a-ade8-49b7-885e-9b685c60cdc6">

**Comment by tabularelf** [comment]
Fixed in [v2.1.0](https://github.com/tabularelf/Canvas/releases/tag/v2.1.0)
